version: "3"
services:
  dashboard:
    image: "dashboard:dev"
    build:
      context: ../app.dashboard/
      dockerfile: infra/development.dockerfile
    ports:
      - "3010:3010"
      - "3001:3001"
      - "3000:3000"
    depends_on: []
    volumes:
      - "../app.dashboard/:/app/"
    environment:
      - NODE_ENV=development
      - DEBUG_COLORS=1
      - DEBUG_HIDE_DATE=1
      - NETWORK__PORT=3000
      - NETWORK__PORT__HMR=3001
      - NETWORK__PORT__BUNDLE_ANALYSER=3010
      - NETWORK__CORS=
      - TEMPLATE__PATH=./index.html
      - "NETWORK__API=http://localhost:4000"
    labels:
      com.list.name: Dashboard
      com.list.link.analyzer: "Bundle analyzer|http://localhost:3010"
  mail-checker:
    image: "mail-checker:dev"
    build:
      context: ../app.mail-checker/
      dockerfile: infra/development.dockerfile
    expose:
      - "4000"
      - "4001"
    ports:
      - "4000:4000"
      - "4001:4001"
    depends_on: []
    volumes:
      - "../app.mail-checker/:/app/"
    environment:
      - NODE_ENV=development
      - DEBUG=gql.*
      - DEBUG_COLORS=1
      - DEBUG_HIDE_DATE=1
      - NETWORK__PORT=4000
      - NETWORK__PORT__DEBUGGER=4001
      - NETWORK__CORS=
      - "DATABASE__URL=postgres://root:123@localhost:5432/rasp"
      - GRPC__PORT=5000
      - GRPC__HOST=mail-checker
    labels:
      com.list.name: Mail checker
  backend:
    image: "backend:dev"
    build:
      context: ../app.backend/
      dockerfile: infra/development.dockerfile
    expose:
      - "5000"
      - "5001"
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on: []
    volumes:
      - "../app.backend/:/app/"
    environment:
      - NODE_ENV=development
      - DEBUG=gql.*
      - DEBUG_COLORS=1
      - DEBUG_HIDE_DATE=1
      - NETWORK__PORT=5000
      - NETWORK__PORT__DEBUGGER=5001
      - NETWORK__CORS=
      - GRPC__PORT=5000
      - GRPC__HOST=backend
    labels:
      com.list.name: Dashboard backend
      com.list.link.endpoint: GraphQL endpoint|/graphql
  board:
    image: "board:dev"
    build:
      context: ../app.board/
      dockerfile: infra/development.dockerfile
    expose:
      - "8000"
      - "8001"
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on: []
    volumes:
      - "../app.board/:/app/"
    environment:
      - NODE_ENV=development
      - DEBUG=gql.*
      - DEBUG_COLORS=1
      - DEBUG_HIDE_DATE=1
      - NETWORK__PORT=8000
      - NETWORK__PORT__DEBUGGER=8001
      - NETWORK__CORS=
      - GRPC__PORT=5000
      - GRPC__HOST=board
    labels:
      com.list.name: Board
