version: '3'

services:
    db:
        image: postgres
        expose:
            - 5432
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: 123
            POSTGRES_DB: rasp_test
