version: '3'

services:
    application:
        build:
            context: ../../
            dockerfile: infra/int/Dockerfile
        expose:
            - '3010'
        ports:
            - '3010'
